"""Fixed achievement table

Revision ID: 834379188238
Revises: 01eba5d4fade
Create Date: 2023-11-20 20:51:30.203911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834379188238'
down_revision = '01eba5d4fade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('delayed', sa.Boolean(), nullable=False))
    op.drop_column('achievement', 'achievement_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('achievement_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('achievement', 'delayed')
    # ### end Alembic commands ###
