"""Fixed streak table

Revision ID: f4fc48ff5a0e
Revises: c856e10689d6
Create Date: 2023-11-18 22:54:56.580169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fc48ff5a0e'
down_revision = 'c856e10689d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
