"""add_tasks_table

Revision ID: 8411f81288b8
Revises: 424ce6c51caf
Create Date: 2023-11-18 14:19:17.701154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8411f81288b8'
down_revision = '424ce6c51caf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
