"""user_init

Revision ID: 01eba5d4fade
Revises: 02f14d84cca8
Create Date: 2023-11-19 20:48:22.632797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01eba5d4fade'
down_revision = '02f14d84cca8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
