"""achievement_streak_tables

Revision ID: c856e10689d6
Revises: fe1e3a9bd646
Create Date: 2023-11-18 19:21:28.493721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c856e10689d6'
down_revision = 'fe1e3a9bd646'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('achievement_date', sa.DateTime(), nullable=True),
    sa.Column('achievement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_type', sa.Integer(), nullable=False),
    sa.Column('achievement_details', sa.String(), nullable=False),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_index(op.f('ix_achievement_achievement_id'), 'achievement', ['achievement_id'], unique=False)
    op.create_table('streaks',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('streak_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('streak_id')
    )
    op.create_index(op.f('ix_streaks_streak_id'), 'streaks', ['streak_id'], unique=False)
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'description')
    op.drop_index(op.f('ix_streaks_streak_id'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_achievement_achievement_id'), table_name='achievement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
