"""roles_permissions_fix_column

Revision ID: 424ce6c51caf
Revises: 230c1f8376b1
Create Date: 2023-11-18 12:45:31.302142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424ce6c51caf'
down_revision = '230c1f8376b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_column('permission', 'role_id_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('role_id_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('permission', 'role_id')
    # ### end Alembic commands ###
