"""add_tasks_table2

Revision ID: bb2e783bfa9a
Revises: a06e39a82db8
Create Date: 2023-11-18 14:22:30.852475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2e783bfa9a'
down_revision = 'a06e39a82db8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
