"""new tables

Revision ID: fbd74ac8405a
Revises: 4dbb00ce4d88
Create Date: 2023-11-18 11:41:43.362748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd74ac8405a'
down_revision = '4dbb00ce4d88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
