"""user_init

Revision ID: 4471763a19eb
Revises: f4fc48ff5a0e
Create Date: 2023-11-19 13:04:24.752150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4471763a19eb'
down_revision = 'f4fc48ff5a0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
