"""permissions_roles_2

Revision ID: fe1e3a9bd646
Revises: bb2e783bfa9a
Create Date: 2023-11-18 14:23:50.279908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1e3a9bd646'
down_revision = 'bb2e783bfa9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
